
services:
  orders-db:
    container_name: teslo_db
    image: 'postgres:15-alpine3.18'
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
