import type { Metadata } from 'next';
import { Sidebar, TopMenu, Footer } from '@/components/ui';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function ShopLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<TopMenu />
			<Sidebar />
			<div className='px-3 sm:px-9'>{children}</div>
			<Footer />
		</>
	);
}
